### PR TITLE
Add uplus to score-dev maintainer

### PR DESCRIPTION
**Pull request by uplus**
スコアサーバ担当になりました。
コラボレータ等々確認したいのでお願いします:pray:

### CODE REVIEW

**Comment by kurochan** [comment]
`role` must be one of member or admin
https://www.terraform.io/docs/providers/github/r/membership.html#role

**Comment by uplus** [comment]
Fixed.

**Comment by uplus** [comment]
@kurochan `role` of `github_team_membership` is different from `team_membership`, it seems to be one of member of maintainer.
https://www.terraform.io/docs/providers/github/r/team_membership.html

**Comment by kurochan** [comment]
🙏🙇🙏🙇🙏🙇

**Comment by uplus** [comment]
I reverted 70cfb8586856905b231e0e4bfa5b4d693e080c57(Fix role). But it is not displayed here.
Should I send a PR again?

**Comment by kurochan** [comment]
お願いします！(特に英語縛りではないです🙏)

**Comment by uplus** [comment]
そうでしたかw
#85 よろしくおねがいします:pray:

**Pull request merged**
